

version: '3.9'

services:
  mariadb:
    container_name: scrapper_container
    image: mysql:8.0
    user: "1000"
    ports:
      - 3307:3306
    volumes:
      - /home/sebas/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=qwerty123
      - MYSQL_USER=normal
      - MYSQL_DATABASE=scrapper_db
