# Generated by Django 4.1.2 on 2022-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceserrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalandologs',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='serviceserrors',
            name='error',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zalandologs',
            name='error',
            field=models.CharField(max_length=20),
        ),
    ]
