# Generated by Django 4.1.2 on 2022-10-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reservedtoscrap_reservedlogs_reserveddailyscraps'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveddailyscraps',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
