# Generated by Django 4.1.2 on 2022-10-11 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reserveddailyscraps_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MohitoToScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MohitoLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=20)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('toscrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservedtoscrap')),
            ],
        ),
        migrations.CreateModel(
            name='MohitoDailyScraps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toscrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservedtoscrap')),
            ],
        ),
    ]
