# Generated by Django 4.1.2 on 2022-10-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mohitotoscrap_mohitologs_mohitodailyscraps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohitodailyscraps',
            name='toscrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mohitotoscrap'),
        ),
        migrations.AlterField(
            model_name='mohitologs',
            name='toscrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mohitotoscrap'),
        ),
    ]
